# Generated by Django 4.2 on 2023-04-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='bathroom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='kitchen',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='paradnaya',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='building',
            name='rooms',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
