# Generated by Django 4.2 on 2023-04-12 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_building_bathroom_building_kitchen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='title',
            new_name='name',
        ),
    ]
